#rem files generated by KEIL
del /s *.crf
del /s *.d
del /s *.htm
del /s *.lnp
del /s *.o
del /s *.plg
del /s *.tra
del /s *.fed
del /s *.dep
del /s *.l1*
del /s *.l2*
del /s *._2i*
#rem files from editing
del /s *.bak
del /s *.*~
del /s *.uvgui.*
del /s *.scvd
del /s *.map
del /s *.sct
del /s *.iex
del /s *.lst